var=term,alacritty
var=rofi,rofi -show drun -show-icons
var=launcher,noctalia msg panel-toggle launcher
var=home,noctalia msg panel-toggle control-center
var=settings,noctalia msg settings-toggle
var=screenshot_region,noctalia msg screenshot-region
var=lock,noctalia msg session lock
var=mango,alacritty -e nvim ~/nixos-dotfiles/config/mango/config.conf

bind=SUPER,r,reload_config
bind=ctrl+Super,q,quit

#Applications 
bind=SUPER,Return,spawn,$term
bind=SUPER+Shift,m,spawn,$mango
bind=SUPER,d,spawn,$rofi
bind=SUPER,a,spawn,$launcher
bind=SUPER,home,spawn,$home
bind=SUPER+Shift,s,spawn,$settings
bind=SUPER,s,spawn_shell,$screenshot_region
bind=SUPER,l,spawn,$lock

#Close window
bind=SUPER,q,killclient

#Keyboard
repeat_rate = 35
repeat_delay = 200

# switch window focus
bind=SUPER,Tab,overcircle,next
bind=ALT,Tab,togglejump
bind=SUPER+shift,n,focusstack,next
bind=SUPER+shift,u,focuslast
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,m,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# switch layout
bind=CTRL+SUPER,i,setlayout,tile
bind=CTRL+SUPER,l,setlayout,scroller
bind=SUPER,n,switch_layout

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

#Workspaces
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

#Move Windows
bind=ctrl+Super,1,tag,1,0
bind=ctrl+Super,2,tag,2,0
bind=ctrl+Super,3,tag,3,0
bind=ctrl+Super,4,tag,4,0
bind=ctrl+Super,5,tag,5,0
bind=ctrl+Super,6,tag,6,0
bind=ctrl+Super,7,tag,7,0
bind=ctrl+Super,8,tag,8,0
bind=ctrl+Super,9,tag,9,0
